- name: install haproxy
  yum:
    name: haproxy-1.5.18
    state: present

- name: copy haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: start and enable haroxy
  systemd:
    name: haproxy
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
