- name: wget calico
  shell: |
    wget https://docs.projectcalico.org/v3.11/manifests/calico.yaml -O /tmp/calico.yaml

- name: update calico file
  shell: |
    sed -i 's#192.168.0.0/16#{{pod_cidr}}#' /tmp/calico.yaml

- name: apply calico
  shell: |
    kubectl apply -f /tmp/calico.yaml